### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by AydanPirani** [acm-uiuc/bifrost#43]
Update logo to be the new ACM logo!

**Comment by Hashimn4** [comment]
Hello. I attempted to contribute to this project by updating the logo. It is my first ever contribution to any open source project. Please let me know if anything went wrong. Thank you.

**Comment by devksingh4** [comment]
> Hashimn4

Unfortunately the patch does not work, issue was meant to be internal so we are closing the issue.
